Repository Global-Tags/LabyAddon, pull requests merged in 2024-12, with the labels that each got.

#75 chore: Add issue templates
  .github/ISSUE_TEMPLATE/1-feature_request.yml
  .github/ISSUE_TEMPLATE/2-bug_report.yml
  .github/ISSUE_TEMPLATE/3-blank-issue.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#76 Use different issue template syntax, add assignee
  .github/ISSUE_TEMPLATE/1-feature_request.yml
  .github/ISSUE_TEMPLATE/2-bug_report.yml
Labels: chore

#77 Fix issue template yml error
  .github/ISSUE_TEMPLATE/1-feature_request.yml
  .github/ISSUE_TEMPLATE/2-bug_report.yml
Labels: bug

#78 man i'm a stupid copy paster
  .github/ISSUE_TEMPLATE/1-feature_request.yml
Labels: bug

#79 Implement Hex color codes
  api/src/main/java/com/rappytv/globaltags/api/GlobalTagAPI.java
  api/src/main/java/com/rappytv/globaltags/api/GlobalTagDeserializer.java
  core/src/main/java/com/rappytv/globaltags/config/widget/TagPreviewWidget.java
Labels: feature

#81 feat: Implement referral leaderboard activity
  api/build.gradle.kts
  api/src/main/java/com/rappytv/globaltags/api/GlobalTagAPI.java
  api/src/main/java/com/rappytv/globaltags/api/Util.java
  core/build.gradle.kts
  core/src/main/java/com/rappytv/globaltags/GlobalTagAddon.java
  core/src/main/java/com/rappytv/globaltags/activities/BanActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/ChangeTagActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/CreateNoteActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/EditBanActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/ReferralLeaderboardActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/ReportUUIDActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/StaffNotesActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/TagHistoryActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/widgets/ReferralLeaderboardEntryWidget.java
  core/src/main/java/com/rappytv/globaltags/activities/widgets/StaffNoteWidget.java
  core/src/main/java/com/rappytv/globaltags/activities/widgets/TagHistoryEntryWidget.java
  core/src/main/java/com/rappytv/globaltags/command/GlobalTagCommand.java
  core/src/main/java/com/rappytv/globaltags/command/subcommands/ClearCacheCommand.java
  core/src/main/java/com/rappytv/globaltags/command/subcommands/LinkSubcommand.java
  core/src/main/java/com/rappytv/globaltags/command/subcommands/RenewCacheCommand.java
  core/src/main/java/com/rappytv/globaltags/command/subcommands/UnlinkSubcommand.java
  core/src/main/java/com/rappytv/globaltags/command/subcommands/VerifyCommand.java
  core/src/main/java/com/rappytv/globaltags/config/GlobalTagConfig.java
  core/src/main/java/com/rappytv/globaltags/config/subconfig/TagSubConfig.java
  core/src/main/java/com/rappytv/globaltags/config/widget/AppealPopup.java
  core/src/main/java/com/rappytv/globaltags/config/widget/TagPreviewWidget.java
  core/src/main/java/com/rappytv/globaltags/interaction/ChangeTagBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/interaction/ClearTagBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/interaction/EditBanInfoBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/interaction/ReferPlayerBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/interaction/ReportBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/interaction/StaffNotesBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/interaction/TagHistoryBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/interaction/ToggleBanBulletPoint.java
  core/src/main/java/com/rappytv/globaltags/listener/BroadcastListener.java
  core/src/main/java/com/rappytv/globaltags/listener/ServerNavigationListener.java
  core/src/main/java/com/rappytv/globaltags/nametag/CustomTag.java
  core/src/main/resources/assets/globaltags/i18n/en_us.json
  core/src/main/resources/assets/globaltags/textures/icon_round.png
  core/src/main/resources/assets/globaltags/themes/fancy/lss/preview.lss
  core/src/main/resources/assets/globaltags/themes/vanilla/lss/leaderboard.lss
  core/src/main/resources/assets/globaltags/themes/vanilla/lss/preview.lss
  settings.gradle.kts
Labels: feature

#83 fix: Some errors were not showing, appeal popup not closing
  api/src/main/java/com/rappytv/globaltags/api/Util.java
  build.gradle.kts
  core/src/main/java/com/rappytv/globaltags/config/widget/AppealPopup.java
Labels: bug

#89 feat: Refetch leaderbords every 5mins
  core/src/main/java/com/rappytv/globaltags/GlobalTagAddon.java
  core/src/main/java/com/rappytv/globaltags/activities/ReferralLeaderboardActivity.java
Labels: feature

#90 feat: Add confirmation checkbox when reporting
  core/src/main/java/com/rappytv/globaltags/activities/EditBanActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/ReportUUIDActivity.java
  core/src/main/resources/assets/globaltags/i18n/en_us.json
  core/src/main/resources/assets/globaltags/themes/fancy/lss/input.lss
  core/src/main/resources/assets/globaltags/themes/vanilla/lss/input.lss
Labels: feature

#93 Release v1.3.7
  api/build.gradle.kts
  build.gradle.kts
  core/build.gradle.kts
  core/src/main/java/com/rappytv/globaltags/GlobalTagAddon.java
  core/src/main/java/com/rappytv/globaltags/activities/EditBanActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/ReferralLeaderboardActivity.java
  core/src/main/java/com/rappytv/globaltags/activities/ReportUUIDActivity.java
  core/src/main/java/com/rappytv/globaltags/config/widget/TagPreviewWidget.java
  core/src/main/java/com/rappytv/globaltags/nametag/CustomTag.java
  core/src/main/resources/assets/globaltags/i18n/de_de.json
  core/src/main/resources/assets/globaltags/i18n/en_us.json
  core/src/main/resources/assets/globaltags/i18n/es_es.json
  core/src/main/resources/assets/globaltags/i18n/ru_ru.json
  core/src/main/resources/assets/globaltags/i18n/tr_tr.json
  core/src/main/resources/assets/globaltags/themes/fancy/lss/input.lss
  core/src/main/resources/assets/globaltags/themes/fancy/lss/preview.lss
  core/src/main/resources/assets/globaltags/themes/vanilla/lss/input.lss
Labels: bug, feature
